sudo: required
dist: trusty
language: java

matrix:
  include:
  - jdk: oraclejdk7
    env: TASK=BUILD

  - jdk: oraclejdk8
    env: TASK=BUILD

  - env: TASK=CHECK_GIT_HISTORY

  allow_failures:
  - env: TASK=CHECK_GIT_HISTORY

before_install:
  - if \[ "$TASK" == "BUILD" \]; then
      mkdir -p $HOME/.gradle ;
      cat gradle/errorprone/warnings > $HOME/.gradle/gradle.properties ;
      cat gradle/errorprone/experimental_errors >> $HOME/.gradle/gradle.properties ;
      cat gradle/errorprone/experimental_warnings  >> $HOME/.gradle/gradle.properties ;
    fi

script:
  - case "$TASK" in
      "CHECK_GIT_HISTORY")
        python check-git-history.py ;;
      "BUILD")
        ./gradlew clean assemble --stacktrace ;
        case "$TRAVIS_JDK_VERSION" in
          "oraclejdk8")
            ./gradlew check :instrumentation-java-all:jacocoTestReport ;;
          "oraclejdk7")
            ./gradlew check ;;
        esac ;;
      *)
        echo "Unknown task $TASK" ;
        exit 1 ;;
    esac

after_success:
  - if \[ "$TASK" == "BUILD" \] && \[ "$TRAVIS_JDK_VERSION" == "oraclejdk8" \]; then
      ./gradlew :instrumentation-java-all:coveralls --stacktrace ;
      bash <(curl -s https://codecov.io/bash) ;
    fi

before_cache:
  - rm -fr $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
