sudo: required
dist: trusty
language: java

matrix:
  include:
  - jdk: openjdk6
    env: BUILD=MVN

  - jdk: oraclejdk7
    env: BUILD=MVN STYLE_CHECK=google_checks.xml

  - jdk: oraclejdk8
    env: BUILD=MVN STYLE_CHECK=google_checks.xml

  - jdk: oraclejdk8
    env: BUILD=MVN STYLE_CHECK=checkstyle_custom_checks.xml

  - jdk: oraclejdk8
    env: BUILD=BAZEL

before_install:
  - case "$BUILD" in
      "BAZEL")
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list ;
        curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add - ;
        sudo apt-get update ;;
    esac

install:
  - case "$BUILD" in
      "BAZEL")
        sudo apt-get install bazel ;;
      "MVN")
        mkdir protoc ;
        cd protoc ;
        curl -L -o protoc.zip https://github.com/google/protobuf/releases/download/v3.0.2/protoc-3.0.2-linux-x86_64.zip ;
        unzip protoc.zip ;
        export PATH=`pwd`/bin/:$PATH ;
        protoc --version ;
        cd .. ;;
    esac

# TODO(sebright) Find a way to disable the "cast" warning only for Protocol Buffer generated code.
script:
  - case "$BUILD" in
      "BAZEL")
        bazel test ... --javacopt=-Werror --javacopt=-Xlint:all --javacopt=-Xlint:-cast ;;
      "MVN")
        case "$TRAVIS_JDK_VERSION" in
          "openjdk6")
            mvn verify -P java6 ;;
          *)
            mvn verify -Dcheckstyle.config=$STYLE_CHECK ;;
        esac
    esac
