sudo: false

language: java

matrix:
  fast_finish: true
  include:
  - jdk: openjdk7
    env: TASK=BUILD
    os: linux

  - jdk: oraclejdk8
    env: TASK=BUILD
    os: linux

  - env: TASK=CHECK_GIT_HISTORY
    os: linux

  # Work around https://github.com/travis-ci/travis-ci/issues/2317
  - env: TASK=BUILD
    os: osx

  allow_failures:
  # Allowing failures because osx builds are very slow.
  - env: TASK=BUILD
    os: osx

before_install:
  - git log --oneline --decorate --graph -30
  - if \[ "$TASK" == "BUILD" \]; then
      mkdir -p $HOME/.gradle ;
      cat gradle/errorprone/warnings > $HOME/.gradle/gradle.properties ;
      cat gradle/errorprone/experimental_errors >> $HOME/.gradle/gradle.properties ;
      cat gradle/errorprone/experimental_warnings  >> $HOME/.gradle/gradle.properties ;
      cat gradle/errorprone/experimental_suggestions  >> $HOME/.gradle/gradle.properties ;
    fi

# Skip Travis' default Gradle install step. See http://stackoverflow.com/a/26575080.
install: true

script:
  # "./gradlew classes testClasses" is a workaround for
  # https://github.com/gradle/gradle/issues/2421.
  # See https://github.com/gradle/gradle/issues/2421#issuecomment-319916874.
  - case "$TASK" in
      "CHECK_GIT_HISTORY")
        python check-git-history.py ;;
      "BUILD")
        export JAVA8_HOME=`jdk_switcher home oraclejdk8` ;
        case "$TRAVIS_JDK_VERSION" in
          "oraclejdk8")
            ./gradlew clean assemble --stacktrace ;
            ./gradlew check :opencensus-all:jacocoTestReport ;;
          "openjdk7")
            jdk_switcher use oraclejdk8 ;
            ./gradlew classes testClasses ;
            jdk_switcher use openjdk7 ;
            ./gradlew clean assemble --stacktrace ;
            ./gradlew check ;;
        esac ;;
      *)
        echo "Unknown task $TASK" ;
        exit 1 ;;
    esac

after_success:
  - if \[ "$TASK" == "BUILD" \] && \[ "$TRAVIS_JDK_VERSION" == "oraclejdk8" \] && \[ "$TRAVIS_OS_NAME" = linux \]; then
      ./gradlew :opencensus-all:coveralls --stacktrace ;
      bash <(curl -s https://codecov.io/bash) ;
    fi

before_cache:
  - rm -fr $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
