sudo: required
dist: trusty
language: java

matrix:
  include:
  - jdk: openjdk6
    env: BUILD=MVN GUAVA_VERSION=19.0

  - jdk: oraclejdk7
    env: BUILD=MVN GUAVA_VERSION=19.0

  - jdk: oraclejdk7
    env: BUILD=MVN GUAVA_VERSION=20.0

  - jdk: oraclejdk8
    env: BUILD=MVN GUAVA_VERSION=19.0

  - jdk: oraclejdk8
    env: BUILD=MVN GUAVA_VERSION=20.0

  - jdk: oraclejdk8
    env: BUILD=MVN GUAVA_VERSION=21.0

  - jdk: oraclejdk8
    env: BUILD=BAZEL

before_install:
  - case "$BUILD" in
      "BAZEL")
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list ;
        curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add - ;
        sudo apt-get update ;;
    esac

install:
  - case "$BUILD" in
      "BAZEL")
        sudo apt-get install bazel ;
        bazel version;;
      "MVN")
        mkdir protoc ;
        cd protoc ;
        curl -L -o protoc.zip https://github.com/google/protobuf/releases/download/v3.0.2/protoc-3.0.2-linux-x86_64.zip ;
        unzip protoc.zip ;
        export PATH=`pwd`/bin/:$PATH ;
        protoc --version ;
        cd .. ;;
    esac

# TODO(sebright) Turn on the deprecation warning after we upgrade to truth 0.31.
# It undeprecates DoubleSubject.isEqualTo(Double).

# TODO(sebright) Find a way to disable the "cast" warning only for Protocol Buffer generated code.

# TODO(bdrutu): Find a way to enable try. We use try-with-resources without
# using the local variable.

# We skip building the tests with Java 6, because they use try-with-resources.
script:
  - case "$BUILD" in
      "BAZEL")
        bazel test ... --javacopt=-Werror --javacopt=-Xlint:all --javacopt=-Xlint:-cast --javacopt=-Xlint:-deprecation --javacopt=-Xlint:-try --config=error_prone_warnings --config=error_prone_experimental_warnings ;;
      "MVN")
        case "$TRAVIS_JDK_VERSION" in
          "oraclejdk8")
            mvn verify -P dev -Dguava.version=$GUAVA_VERSION ;;
          "openjdk6")
            mvn verify -Dmaven.test.skip -Dguava.version=$GUAVA_VERSION ;;
          *)
            mvn verify -Dguava.version=$GUAVA_VERSION ;;
        esac
    esac
